[package]
name = "ground"
version = "0.1.0"
edition = "2021"

[dependencies]
rfe.path = "../../rfe"
rfe.features = ["std", "reflect"]
anyhow.workspace = true
simple_logger = "5.0.0"
log.workspace = true
egui = "0.30.0"
eframe = "0.30.0"
