[package]
name = "macros"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/macros.rs"
proc-macro = true


[dependencies]
proc-macro2 = "1.0.89"
quote = "1.0.37"
syn = { version = "2.0.87", features = ["full"] }
